FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# MajesticThai

Polls is a simple API allowing consumers to view polls and vote in them.

## Dishes Collection [/dishes]

### List All Dishes [GET]

+ Response 200 (application/json)

        [
            {
                "url": "/dishes",
                "dishes": [
                    {
                      'id': 101,
                      'item': 'Green Curry',
                      'description': 'Zucchini, eggplant, green beans and basil leaves, simmered in a spicy green curry paste with coconut milk.',
                      'price': 9.99
                      }, {
                      'id': 102,
                      'item': 'Red Curry',
                      'description': 'Bell peppers, bamboo shoots, eggplant and basil leaves. This is simmered in a red curry paste with coconut milk.',
                      'price': 9.99
                      }, {
                      'id': 103,
                      'item': 'Yellow Curry',
                      'description': 'Mild yellow curry, containing rich flavors of curry powder, coconut milk, potatoes, onions and carrots.',
                      'price': 7.99
                      }, {
                      'id': 104,
                      'item': 'Pa-Neng Curry',
                      'description': 'Sweet thick paste of pa-neng curry, coconut milk, bell peppers and basil leaves.',
                      'price': 11.99
                      }, {
                      'id': 106,
                      'item': 'Massaman Curry',
                      'description': 'This is a favorite Thai curry with potatoes, onions, and peanuts in coconut milk.',
                      'price': 8.99
                      }, {
                      'id': 107,
                      'item': 'Pineapple Curry',
                      'description': 'Diced pineapples, bell peppers, basil leaves, in spicy Thai red curry paste.',
                      'price': 10.99
                      }, {
                      'id': 108,
                      'item': 'Jungle Curry',
                      'description': 'With choice of meat, bell peppers, green beans, squash, bamboo shoots, basil, mushrooms, baby corn, all cooked with jungle curry paste.',
                      'price': 12.99
                      }, {
                      'id': 109,
                      'item': 'Roasted Duck Curry',
                      'description': 'Sliced roasted duck with pineapple chunks, tomato, bell pepper and basil in red curry paste and coconut mlk.',
                      'price': 13.99
                    }
                ]
            }
        ]
        
## Dish Model [/dishes/{id}]


### List Indiviual Dishes [GET]

+ response 200 (application/json)

        {
            "url": "/dishes/1",
            "dish": [
                {
                    'id': 101,
                     'item': 'Green Curry',
                     'description': 'Zucchini, eggplant, green beans and basil leaves, simmered in a spicy green curry paste with coconut milk.',
                     'price': 9.99
                }
            ]
        }

## Order Collection [/orders]

### List All Orders [GET]

+ response 200 (application/json)

        [
            {
                "url": "/orders",
                "orders": [
                {
                'id': 1,
                'username': 'bob',
                'time': '12:00',
                'total': '24.00',
                'ordered items': [
                'soup',
                'noodles',
                'rice']
                },
                {
                'id': 2,
                'username': 'jim',
                'time': '18:00',
                'total': '36.00',
                'ordered items': [
                'soup',
                'noodles',
                'rice',
                'rolls',
                'drink']
                }
                ]
            }
        ]
        
## Order Model [/orders/{id}]


### List Indiviual Orders [GET]

+ response 200 (application/json)

        {
            "url": "/orders/1",
            "dish": [
                {
                    'id': 1,
                     'username': 'bob',
                'time': '12:00',
                'total': '24.00',
                'ordered items': [
                'soup',
                'noodles',
                'rice']
                }
            ]
        }